### PR TITLE
fast worker

### PR DESCRIPTION
**Pull request by soliton4**
you asked for it

this is a faster implementation of the worker thread.
unfortunately the storydemo.html is broken at the moment because of 
https://github.com/mbebenita/Broadway/issues/40

but i tested it with a reverted version and i get a framerate that is slightly higher than the non worker version

to test it with a working video do a:
git checkout 1afd2e2d1b32d85e7cb65070a71793405e0657a8

then cherry pick this commit or simply copy the fast-worker.js, mp4.js and storydemo.html from this pr.

have fun ;p

### CODE REVIEW

**Comment by saste** [comment]
Unfortunately I can't test this, because of:
https://github.com/mbebenita/Broadway/issues/45

**Comment by saimamahmood** [comment]
I just tested, by changing/adding the 3 files you specified. It seems as though the worker thread is still playing pretty slowly.

**Comment by soliton4** [comment]
@saimamahmood 
this line is the secret
https://github.com/mbebenita/Broadway/pull/43/files#diff-3c49a8e3fc6defe880bbc60637820ecbR41
"secret"

it changes the ownership of the binary instead of copying it.
on my system it makes the worker go even faster than the non worker solution

**Comment by mbebenita** [comment]
@soliton4 since I'm not actively maintaining Broadway.js or doing reviews, I can give you push access to the repo if you'd like.

**Comment by soliton4** [comment]
hi @mbebenita , funny you ask

i was actually thinking about forking it ;)
but i didnt have the time yet.

since there is so much demand for broadway and i feel kinda fit to maintain it your proposal is probably a good idea.

can i notice you about updating the demo sites or can i push new versions to there as well?

thank you

**Comment by mbebenita** [comment]
@soliton4 great, you should have full access now. Fell free to update the demos as well.

**Comment by samsamm777** [comment]
this is great news. ill certainly have a lot of input on this too!

**Comment by soliton4** [comment]
@mbebenita status:
the demos in the repos work now in chrome and ff  
i went through all the issues - closed the obvious ones and tried to get status on the others.  

plans for the future are: 
- get the asm.js fallback integrated  
- get the fast worker integrated  
- provide a universal module loader  

is there a blog site? should we create one?

**Comment by soliton4** [comment]
replaced by 
https://github.com/mbebenita/Broadway/commit/cc24730c40033fe590275a9e671498ae2d44cc64

**Pull request closed without merging**
