### PR TITLE
fix asm.js validation in asmFactory

### PR DESCRIPTION
**Pull request by kripken**
This fixes asm validation problems in asmFactory, the hand-written asm module in the output.

### CODE REVIEW

**Comment by kripken** [comment]
Add what?

**Comment by soliton4** [comment]
the new rule

**Comment by BrendanEich** [comment]
There is no new rule to add to the asm.js spec.

/be

**Comment by kripken** [comment]
Yes, I think there must have been a bug in Firefox that was fixed, if that used to validate. Arguments need to be coerced to a type.

**Comment by soliton4** [comment]
i used https://github.com/dherman/asm.js to validate the code and it went through.
so there is obviosly a rule missing.

you seem to be more into asm.js than me. maybe you could easily add it

**Comment by BrendanEich** [comment]
Could be a bug in the validator -- you have the spec, and the asm.js NPM module, so I wouldn't assume it must be a spec bug. Cc'ing @dherman.

/be

**Comment by kripken** [comment]
Yes, the validator is not alwayst up to date, I think. It's best to check in (recent) Firefox.

**Comment by soliton4** [comment]
no offense but i think its best to update the validator

**Comment by BrendanEich** [comment]
No offense taken, but you're in the wrong github repo to file an issue on the validator :-/. I've included @dherman and hope he'll take it from here. Thanks.

/be

**Comment by kripken** [comment]
I filed an issue on the asm repo with the validator.

**Comment by soliton4** [comment]
:thumbsup: @kripken

**Comment by BrendanEich** [comment]
Thanks, @kripken!

**Comment by BrendanEich** [comment]
And thanks @soliton4 for being so active and having an awesome github user name :-).

/be

**Pull request merged**
